"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 200

[aws]
symbol = "îŒ½  "
format = "\\[[$symbol($profile)(\\($region\\))(\\[$duration\\])]($style)\\]"

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "
format = "\\[[$symbol($version(-$name))]($style)\\]"

[conda]
symbol = "ï„Œ "
format = "\\[[$symbol$environment]($style)\\]"

[dart]
symbol = "î˜ "
format = "\\[[$symbol($version)]($style)\\]"

[directory]
read_only = " ó°Œ¾"
truncation_length = 0

[docker_context]
symbol = "ïŒˆ "
format = "\\[[$symbol$context]($style)\\]"

[elixir]
symbol = "î‰µ "
format = "\\[[$symbol($version \\(OTP $otp_version\\))]($style)\\]"

[elm]
symbol = "î˜¬ "
format = "\\[[$symbol($version)]($style)\\]"

[git_branch]
symbol = "ï˜ "
format = "\\[[$symbol$branch]($style)\\]"

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style))"
#format = '[\($all_status$ahead_behind\)]($style) '
style = "177"
conflicted = "ï±"
up_to_date = " ó°„¬"
untracked = "î¬²"
ahead = "ï…¶${count}"
diverged = "ï½ï…¶${ahead_count}ï…µ${behind_count}"
behind = "ï…µ${count}"
stashed = "ó°— "
modified = "ï‘ˆ "
staged = '[ï­œ\($count\)]($style)'
renamed = "ï‘š"
deleted = "ï€”"

[golang]
symbol = "î˜§ "
format = "\\[[$symbol($version)]($style)\\]"

[haskell]
symbol = "î· "
format = "\\[[$symbol($version)]($style)\\]"

[hg_branch]
symbol = "ï˜ "
format = "\\[[$symbol$branch]($style)\\]"

[java]
symbol = "î‰– "
format = "\\[[$symbol($version)]($style)\\]"

[julia]
symbol = "î˜¤ "
format = "\\[[$symbol($version)]($style)\\]"

[lua]
symbol = "î˜  "
format = "\\[[$symbol($version)]($style)\\]"

[memory_usage]
symbol = "ó°› "
format = "\\[$symbol[$ram( | $swap)]($style)\\]"

[meson]
symbol = "ó°”· "
format = "\\[[$symbol$project]($style)\\]"

[nim]
symbol = "î™· "
format = "\\[[$symbol($version)]($style)\\]"

[nix_shell]
symbol = "ïŒ“ "
format = "\\[[$symbol$state( \\($name\\))]($style)\\]"

[nodejs]
symbol = "îœ˜ "
format = "\\[[$symbol($version)]($style)\\]"

[package]
symbol = "ó°– "
format = "\\[[$symbol$version]($style)\\]"

[python]
symbol = "îˆµ "
format = "\\[[${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\))]($style)\\]"

[rlang]
symbol = "ï³’ "

[ruby]
symbol = "î‘ "
format = "\\[[$symbol($version)]($style)\\]"

[rust]
symbol = "î¨ "
format = "\\[[$symbol($version)]($style)\\]"

[scala]
symbol = "îœ· "
format = "\\[[$symbol($version)]($style)\\]"

[spack]
symbol = "ğŸ…¢ "
format = "\\[[$symbol$environment]($style)\\]"

[bun]
format = "\\[[$symbol($version)]($style)\\]"

[cmake]
format = "\\[[$symbol($version)]($style)\\]"

[cmd_duration]
format = "\\[[ó°”› $duration]($style)\\]"

[cobol]
format = "\\[[$symbol($version)]($style)\\]"

[crystal]
format = "\\[[$symbol($version)]($style)\\]"

[daml]
format = "\\[[$symbol($version)]($style)\\]"

[deno]
format = "\\[[$symbol($version)]($style)\\]"

[dotnet]
format = "\\[[$symbol($version)( $tfm)]($style)\\]"

[erlang]
format = "\\[[$symbol($version)]($style)\\]"

[gcloud]
format = "\\[[$symbol$account(@$domain)(\\($region\\))]($style)\\]"


[helm]
format = "\\[[$symbol($version)]($style)\\]"

[kotlin]
format = "\\[[$symbol($version)]($style)\\]"

[kubernetes]
format = "\\[[$symbol$context( \\($namespace\\))]($style)\\]"

[ocaml]
format = "\\[[$symbol($version)(\\($switch_indicator$switch_name\\))]($style)\\]"

[openstack]
format = "\\[[$symbol$cloud(\\($project\\))]($style)\\]"

[perl]
format = "\\[[$symbol($version)]($style)\\]"

[php]
format = "\\[[$symbol($version)]($style)\\]"

[pulumi]
format = "\\[[$symbol$stack]($style)\\]"

[purescript]
format = "\\[[$symbol($version)]($style)\\]"

[raku]
format = "\\[[$symbol($version-$vm_version)]($style)\\]"

[red]
format = "\\[[$symbol($version)]($style)\\]"

[sudo]
format = "\\[[as $symbol]\\]"

[swift]
format = "\\[[$symbol($version)]($style)\\]"

[terraform]
format = "\\[[$symbol$workspace]($style)\\]"

[time]
format = "\\[[$time]($style)\\]"

[username]
format = "\\[[$user]($style)\\]"

[vagrant]
format = "\\[[$symbol($version)]($style)\\]"

[vlang]
format = "\\[[$symbol($version)]($style)\\]"

[zig]
format = "\\[[$symbol($version)]($style)\\]"
